name: html_toolbox
author: David Bernard <david.bernard.31@gmail.com>
version: 0.3.0-dev
homepage: https://github.com/davidB/html_toolbox
description: A toolbox for commons operations on html.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  bot: '>=0.26.0 <0.27.0'
